source 'https://rubygems.org'

## Let's force the version number so that we can use our own build here
gem 'dashing', '=1.3.6'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
